languageCode = "pt-br"
languageName = "Português (Brasil)"
weight = 1
title = "Engenharia da Computação UABJ"

[params]
  displayName = "Português (Brasil)"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Site oficial do curso de Engenharia da Computação da UABJ."

[params.author]
  name = "Coordenação de Engenharia da Computação UABJ"
  email = "engenharia.computacao@ufrpe.br"
  image = "img/blowfish_logo.png"
  headline = "Computação UABJ."
  bio = "Coordenação de Engenharia da Computação UABJ."
  links = [
    { github = "https://https://github.com/Computacao-UABJ" },
  ]
