languageCode = "en"
languageName = "English"
weight = 2
title = "Computer Engineering UABJ"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Coordination of Computer Engineering UABJ"
  email = "nuno@n9o.xyz"
  image = "img/blowfish_logo.png"
  headline = "Computer Engineering UABJ."
  bio = "Coordination of Computer Engineering UABJ."
  links = [
    { github = "https://https://github.com/Computacao-UABJ" },
  ]