# -- Menu Principal --
# O menu principal é exibido no cabeçalho no topo da página.

[[main]]
  name = "O curso"
  pageRef = "course"
  weight = 10

[[main]]
  name = "Professores"
  pageRef = "professors"
  weight = 15

[[main]]
  name = "Pesquisa e Extensão"
  pageRef = "actions"
  weight = 20

[[main]]
  name = "Contate nos"
  pageRef = "contact"
  weight = 25

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 400


# -- Menu de Rodapé --

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Autores"
   pageRef = "authors"
   weight = 20
